// SOCKETS
export const SOCKET_INIT = 'SOCKET_INIT';
export const SOCKET_CONNECTED = 'SOCKET_CONNECTED';
export const SOCKET_CLOSED = 'SOCKET_CLOSED';

// ACTIVE ORDERS
export const GET_ACTIVE_ORDERS = 'GET_ACTIVE_ORDERS';
export const GET_CREATED_ORDERS = 'GET_CREATED_ORDERS';
export const GET_COOKED_ORDERS = 'GET_COOKED_ORDERS';

// ORDER HISTORY
export const GET_ORDER_HISTORY = 'GET_ORDER_HISTORY';

// UPDATE ORDER
export const UPDATE_ORDER = 'UPDATE_ORDER';